from .spec import meta, spec, Spec
from .data import parquet, csv, spatial, table, data
from .params import param, selection
from .encodings import (
    sql,
    count,
    sum,
    avg,
    mean,
    min,
    max,
    median,
    argmax,
    argmin,
    bin,
    date_month,
    date_month_day,
    centroid_x,
    centroid_y,
    column,
    geojson,
    channels,
)
from .plot import (
    plot,
    source,
    rule_y,
    rule_x,
    line_y,
    line_x,
    bar_y,
    bar_x,
    area_y,
    area_x,
    text,
    dot,
    density,
    y_grid,
    y_label,
    y_tick_format,
    x_tick_format,
    x_axis,
    y_axis,
    x_label,
    x_label_anchor,
    y_label_anchor,
    r_range,
    color_domain,
    color_scale,
    x_tick_size,
    y_tick_size,
    width,
    height,
    margins,
    vconcat,
    hconcat,
    vspace,
    hspace,
    mark,
    directive,
    slider,
    select,
    checkbox,
    menu,
    search,
    table_input,
    input,
    option,
    brush,
    sort,
    interval_x,
    interval_y,
    interval_xy,
    toggle,
    toggle_x,
    toggle_y,
    toggle_color,
    nearest_x,
    nearest_y,
    region,
    highlight,
    pan,
    pan_x,
    pan_y,
    pan_zoom,
    pan_zoom_x,
    pan_zoom_y,
    color_legend,
    opacity_legend,
    symbol_legend,
)

__all__ = [
    "meta",
    "spec",
    "Spec",
    "parquet",
    "csv",
    "spatial",
    "table",
    "data",
    "param",
    "selection",
    "plot",
    "source",
    "mark",
    "rule_y",
    "rule_x",
    "line_y",
    "line_x",
    "bar_y",
    "bar_x",
    "area_y",
    "area_x",
    "text",
    "dot",
    "density",
    "y_grid",
    "y_label",
    "y_tick_format",
    "x_tick_format",
    "x_axis",
    "y_axis",
    "x_label",
    "x_label_anchor",
    "y_label_anchor",
    "r_range",
    "color_domain",
    "color_scale",
    "x_tick_size",
    "y_tick_size",
    "width",
    "height",
    "margins",
    "vconcat",
    "hconcat",
    "vspace",
    "hspace",
    "directive",
    "slider",
    "select",
    "checkbox",
    "menu",
    "search",
    "table_input",
    "input",
    "option",
    "brush",
    "sort",
    "interval_x",
    "interval_y",
    "interval_xy",
    "toggle",
    "toggle_x",
    "toggle_y",
    "toggle_color",
    "nearest_x",
    "nearest_y",
    "region",
    "highlight",
    "pan",
    "pan_x",
    "pan_y",
    "pan_zoom",
    "pan_zoom_x",
    "pan_zoom_y",
    "color_legend",
    "opacity_legend",
    "symbol_legend",
    "sql",
    "count",
    "sum",
    "avg",
    "mean",
    "min",
    "max",
    "median",
    "argmax",
    "argmin",
    "bin",
    "date_month",
    "date_month_day",
    "centroid_x",
    "centroid_y",
    "column",
    "geojson",
    "channels",
]


def __getattr__(name: str):
    """Dynamic mark/directive factory for names not explicitly exported.

    Allows any snake_case mark or directive to be used without an explicit
    function definition, e.g.::
    """
    if name.startswith("_"):
        raise AttributeError(name)

    from .plot import Directive, Mark
    from .util import camelize

    camel = camelize(name)

    def _factory(*args, data=None, **kwargs):
        if len(args) == 1 and data is None and not kwargs:
            # Single positional arg to directive
            return Directive(camel, args[0])
        # otherwise creates a mark
        return Mark(camel, data=data, enc=kwargs if kwargs else None)

    _factory.__name__ = name
    _factory.__qualname__ = f"vgplot.{name}"
    return _factory
