[project]
name = "schema-wrapper"
version = "0.1.0"
description = "Schema wrapper classes for Mosaic"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pyyaml",
    "narwhals"
]

[project.urls]
homepage = "https://github.com/uwdata/mosaic"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "jupyterlab>=4.2.5",
    "mypy>=1.11.1",
    "pytest>=7.4.4",
    "pytest-cov",
    "ruff>=0.6.1",
    "pandas",
    "mosaic-widget"
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
files = "src/**/*.py"
strict = false
ignore_missing_imports = true
